### ISSUE TITLE
enter passphrase in terminal while private key authentication

### ISSUE THREAD

**Issue by HankAviator** [carlolars/gnupg2-msys2#1]
Hello! Your post is working like charm, only one common issue that happens to all platforms: pinentry GUI will pop up when any private key authentication is needed.

PATH is automatically configured by GPG4Win, appending `C:\Program Files (x86)\Gpg4win\..\GnuPG\bin`. As many other pages, like [this one](https://superuser.com/questions/991191/how-to-prevent-the-popup-password-prompt-when-using-gnupg-with-mutt) suggest `pinentry-(curses|tty)` which both packages don't exist in mingw pacman package repo.

I found [this page](https://superuser.com/questions/1189602/how-to-configure-gpg2-to-ask-for-passphrase-on-the-console-instead-of-in-a-popup) exactly what I'm trying to solve now and I tried what he did too, this post has no answer yet. I tried to create and modify `%APPDATA%\gnupg\gpg-agent.conf` and added `pinentry-program "c:/Program Files (x86)/GnuPG/bin/pinentry-basic.exe"` (note the paired double quotes). On the contrary to what was mentioned on the page, I could call `pinentry-basic`, though it's also a pop-up:
![image](https://user-images.githubusercontent.com/8069557/39670110-2385424a-5130-11e8-9cb0-b1d7e6e06905.png)

... which is actually different from what `GPG4win` has to offer:
![image](https://user-images.githubusercontent.com/8069557/39670117-455122e0-5130-11e8-9f0d-4fc34e3874a1.png)

Solution found in the end:
`allow-loopback-pinentry`is the default option for `gpg-agent`, simply add `pinentry-mode loopback` to `%APPDATA%\gnupg\gpg.conf` then run `gpgconf --kill gpg-agent ; gpg-connect-agent /bye` in PowerShell will do the trick.

I'm keeping the exploration process here as a reference, thanks again!

**Comment by carlolars** [comment]
Thanks!

**Comment by semsel123** [comment]
Hello,
I am trying to suppress passphrase prompt completely as we are looking for a fully automated unattended decryption program. I am using Task Scheduler to run the below command
echo mypassphrase|gpg --logger-file "D:\FileShare\PGPScripts\SFTP\gpglog.log"  --pinentry-mode loopback --batch --yes --passphrase-fd 0  --decrypt-files "D:\FileShare\Concur\WIP\*.pgp"

After the system goes idle the decryption starts failing with the error "Bad Passphrase/ Secret key available". After running a manual decryption, the job continues to run successfully.

What should I do to get rid of this problem?

Are the below options going to be helpful in my case?

add pinentry-mode loopback to %APPDATA%\gnupg\gpg.conf;
 then run gpgconf --kill gpg-agent ;
